### ISSUE TITLE
Guardrail doesn't support Array type for Form Params

### ISSUE THREAD

**Issue by imorrison** [twilio/guardrail#122]
If you add something like 

```
- name: MediaUrl
   in: formData
   description: Media Urls
   required: false
   type: array
   items:
       type: string
```

Guardrail generates `("MediaUrl", mediaUrl.map(Formatter.show(_)))` in the `FormData`, which doesn't compile.
