### ISSUE TITLE
`TextPlain` `in: body` does not permit non-string values

### ISSUE THREAD

**Issue by blast-hardcheese** [twilio/guardrail#144]
The following did not compile, and probably still does not compile. Opening a ticket to track it.
```yaml
      parameters:
        - name: epoch_seconds
          in: body
          required: true
          schema:
            type: integer
            format: int64
```
