### ISSUE TITLE
x-scala-empty-is-null does not work with snake-cased parameters

### ISSUE THREAD

**Issue by blast-hardcheese** [twilio/guardrail#145]
Given the following definition:
```yaml
definitions:
  Foo:
    type: object
    properties:
      bar_baz:
        type: string
        x-scala-type: NonEmptyString
        x-scala-empty-is-null: true
```
`x-scala-empty-is-null` does not seem to do anything. Changing the spec to just be `bar` or just `baz` produces the expected behaviour (`flatMap`ping on the parsed string value, sinking to `null` if empty).

I've traced this through and found [`if (emptyToNullKeys contains param.name)`](https://github.com/twilio/guardrail/blob/20fb0bcfb136b8825dc027d4d28abbbf9c4a1d39/modules/codegen/src/main/scala/com/twilio/guardrail/generators/CirceProtocolGenerator.scala#L261) compares the normalized parameter name to the original parameter name. Suggestion is to replace this code with a boolean, as we're threading through the same value in two different fields, just to do an incorrect comparison at the end.
