### ISSUE TITLE
dashed-case conversion doesn't work for mixed case

### ISSUE THREAD

**Issue by blast-hardcheese** [twilio/guardrail#153]
Defining the following parameter:
```yaml
        - in: header
          name: X-Auth-User
          type: integer
          format: int64
          required: true
```

yields the following argument:
```scala
`x-Auth-User`: Long
```

whereas altering the case to
```yaml
        - in: header
          name: x-auth-user
          type: integer
          format: int64
          required: true
```

generates
```scala
xAuthUser: Long
```
