### ISSUE TITLE
http4s generator is missing an import

### ISSUE THREAD

**Issue by countfloyd** [twilio/guardrail#180]
Added a parameter for an endpoint:

```
      parameters:
        - name: Authentication
          description: token obtained from login
          in: header
          required: true
          type: string
```

and got a compile error because it's missing

```
import org.http4s.implicits._
```

to get the 'ci' method in StringOps
