### ISSUE TITLE
Question: Can I override name of generated case classes?

### ISSUE THREAD

**Issue by eli-jordan** [twilio/guardrail#354]
1. Is it possible to override the names of the generated cases classes for my model types?

e.g. In the schema below a case class called `Foo` would be generated. Is it possible to change the to a different name without changing the `Foo` attribute. I'd like the entity to be called `Foo` in our docs, but `FooApi` internally in the code.

```yaml
definitions:
    Foo:
        type: object
        properties:
           ...
```

2. Is there a Gitter/Slack room where questions such as this should be directed?
