### ISSUE TITLE
Anonymous enum support

### ISSUE THREAD

**Issue by hanny24** [twilio/guardrail#370]
We should support anonymous enums. Given this definition:

```
  Foo:
    type: object
    properties:
      value:
        type: string
        enum: [X, Y]
```

we should generate `sealed trait Value` in a companion object of `Foo`. Currently `value` has type `String`.
