### ISSUE TITLE
Custom types don't work for array items

### ISSUE THREAD

**Issue by kelnos** [twilio/guardrail#389]
This does not work as expected:
```
components:
  schemas:
    Foo:
      customArray:
        type: array
        items:
          type: object
          x-jvm-type: Bar
```
We'd expect to see `case class Foo(customArray: IndexedSeq[Bar])` but instead we see `IndexedSeq[io.circe.Json]`.

As a workaround, moving out of `items` and doing
```
x-java-type: List<Bar>
x-scala-type: IndexedSeq[Bar]
```
works, but is a bit annoying.
