### ISSUE TITLE
identifier expected but integer literal found

### ISSUE THREAD

**Issue by nb-ceffa** [twilio/guardrail#428]
For swagger definition:
```
---
type: object
properties:
  STATUS_CODE:
    type: string
    enum: [0, 1]
    description: >
      Status Code:
       * '0' - success
       * '1' - error
```
guardrail generates case object like `case object 0 extends StatusCode("0")` so it will returns an error like `identifier expected but integer literal found.`

Could you please fix this issue?

cc. @tomasherman
