### ISSUE TITLE
List / array in body param is rendering vague List<JsonNode> java code

### ISSUE THREAD

**Issue by one-raghav** [twilio/guardrail#433]
when an API is required to accept a `list` in body params, generated `java` code is not accurate.

example:
```
        - required: true
          name: body
          description: body string array
          schema:
            type: array
            items:
              type: string
          in: body 
```

generates 
```
final java.util.List<com.fasterxml.jackson.databind.JsonNode>
```

if the schema is changed with `#ref`, generated code is accurate.

example:
```
  StringArray:
    example: SC00000000000000000000000000000001
    type: array
    items:
       type: string
```
```
        - required: true
          name: body
          description: my strings array
          schema:
             $ref: '#/definitions/StringArray'
          in: body
```
generates 
```
final java.util.List<String>
```
