### ISSUE TITLE
required Query Parameters are actually nullable

### ISSUE THREAD

**Issue by lorenzotomasini** [twilio/guardrail#482]
Generating code in `java` dropwizard.

When defining query parameters as:

```
MyQueryParameter:
      required: true
      in: query
      name: MyParameter
      schema:
        type: string
```

the generated parameter is indeed not `Optional`, however if the parameter is not passed by the client, null is threaded to the resource handler implementation.
