### ISSUE TITLE
Scala enum parsing tries to booleanify names

### ISSUE THREAD

**Issue by kelnos** [twilio/guardrail#632]
This is bizarre:
```
components:
  schemas:
    OnOff:
      type: string
      enum:
        - off
        - on
```
... generates:
```
object OnOff {
  object members {
    case object False extends OnOff("false")
    case object True extends OnOff("true")
  }
}
```
Not only are the names weird, but the values are invalid.
