### ISSUE TITLE
Properties named `class` cause compilation issues

### ISSUE THREAD

**Issue by childish-sambino** [twilio/guardrail#862]
One of my schemas contains an object property named `class`:

```
components:
  schemas:
    ResponseLog:
      type: object
      properties:
        class:
          type: string
```

This generates the getter like so:
```
    public Optional<String> getClass() {
        return this.class_;
    }
```

Which is not allowed:
> 'getClass()' cannot override 'getClass()' in 'java.lang.Object'; overridden method is final
